Type declarations
WordPress/wpcs-docs pull request #102
Opened 2022-08-12 15:06 UTC by dingo-d

This PR depends on #101. Once that is merged, this PR should be rebased to the master branch.

The PR adds rules about the type declaration rules and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

2022-08-14 11:36 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +- The scalar `bool`, `int`, `float` and `string` type declarations can not be used until the minimum PHP version has been raised to PHP 7.0.
```suggestion
- The scalar `bool`, `int`, `float`, and `string` type declarations can not be used until the minimum PHP version has been raised to PHP 7.0.
```

2022-08-14 11:36 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +- The `iterable`, `void` and `object` type declarations can not be used until the minimum PHP version has been raised to PHP 7.1 and 7.2 respectively.
```suggestion
- The `iterable`, `void`, and `object` type declarations can not be used until the minimum PHP version has been raised to PHP 7.1 and 7.2 respectively.
```

Alternatively, split these up into separate bullets for PHP 7.1 and PHP 7.2.

2022-08-14 11:36 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +Property type declarations can not be used until the minimum PHP version has been raised to PHP 7.4.
```suggestion
- Property type declarations can not be used until the minimum PHP version has been raised to PHP 7.4.
```

2022-08-14 11:36 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +In WordPress Core, type declaration usage has the following restrictions based on the minimum required PHP version:
> In WordPress Core,...

Surely this also applies to any plugin or theme as well, not just WP core?

2022-08-14 11:36 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +): ?\Class_Name {
```suggestion
): iterable {
```

Just to mix it up a little as the `foo()` function above also returns the exact same type, and it's good to see a non-null, non-FQCN example.

2022-08-14 16:10 UTC, dingo-d commented on wordpress-coding-standards/php.md
> +In WordPress Core, type declaration usage has the following restrictions based on the minimum required PHP version:
Valid point 👍🏼 I will remove the part about the WP Core.

2022-08-14 16:12 UTC, dingo-d commented on wordpress-coding-standards/php.md
> +- The `iterable`, `void` and `object` type declarations can not be used until the minimum PHP version has been raised to PHP 7.1 and 7.2 respectively.
Splitting these might make more sense, seeing how others are split by versions 👍🏼

2022-08-20 11:28 UTC, dingo-d commented
I've added all the types currently available that cannot be used in core (still), but since the wording in the alert now excludes core I've reworded the phrase `until the minimum version is raised` to `until the minimum PHP version is ... or higher`. Because it didn't really make sense (as there is no mention of WordPress, so where the PHP minimum required version comes from wasn't really clear to me in the sentence context).

I'm open to rewording these statements if they read weird in any way.

2022-08-26 10:28 UTC, jrfnl requested changes
Gone through it with a fine toothcomb....

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +- `never` return type cannot be used until the minimum PHP version is PHP 8.1 or higher.
```suggestion
- `never` (return type only) cannot be used until the minimum PHP version is PHP 8.1 or higher.
- Disjunctive normal form types (combining union types and intersection types) cannot be used until the minimum PHP version is PHP 8.2 or higher.
```

Might as well anticipate on PHP 8.2 as otherwise we'd need to edit this again in a few months time.

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +[alert]
Like with other new sections, I would move this part (the `alert` box) to the bottom of the section _after_ the CS rules (as these are not CS rules, but information about the PHP feature).

Also: is `alert` the red style ? Should this maybe be an info box (blue IIRC) instead ?

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +Type declarations must have exactly one space before and after the type. The nullability operator (`?`) is regarded as part of the type declaration and there should be no space between this operator
```suggestion
Type declarations must have exactly one space before and after the type. The nullability operator (`?`) is regarded as part of the type declaration and there should be no space between this operator and the actual type. Class/interface/enum name based type declarations should use the case of the class/interface/enum name as declared, while the keyword-based type declarations should be lowercased.
```

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +These rules apply to all structures allowing for type declarations: functions, closures, catch conditions as well as the PHP 7.4 arrow functions and typed properties.
```suggestion
These rules apply to all structures allowing for type declarations: functions, closures, enums, catch conditions as well as the PHP 7.4 arrow functions and typed properties.
```

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +The following examples showcase what type hints are currently available in the WordPress Core due to the minimum supported PHP version
```suggestion
The following examples showcase what type declarations are currently available in WordPress Core due to the minimum supported PHP version:
```

To be honest, I'd be tempted to say: combine the two sets of examples. The info/alert boxes at the bottom will contain the info on what can be used in Core and what not.

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +This leaves, for now, only unconditionally declared functions in the global namespace, `private` class methods, and code newly being introduced as candidates for adding type declarations.
```suggestion
This leaves, for now, only unconditionally declared functions in the global namespace, `private` class methods, and code  new to Core, as candidates for adding type declarations.
```

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +This includes all existing `public` and `protected` class methods and any conditionally declared (pluggable) functions in the global namespace.
I think this sentence can be left out.

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +While rare, `array` and class/interface name based type declarations already exist in WordPress Core.
I think this sentence can be left out.

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +For those, adding `callable`, class and interface name based parameter type declarations where the parameter type only expects one type and it would allow for simplification of existing/new code, is
I think this sentence can be left out.

2022-08-26 10:28 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +Using the `array` keyword in type declarations is **strongly discouraged** for now, as most often, it would be better to use `iterable` to allow for more flexibility in the implementation and that ke
If the "leave out" suggestions would be applied, I think this should be prefixed with "Note:".

```suggestion
Note: Using the `array` keyword in type declarations is **strongly discouraged** for now, as most often, it would be better to use `iterable` to allow for more flexibility in the implementation and that keyword is not yet available for use in WordPress Core until the minimum requirements are raised to PHP 7.1.
```

2022-08-26 10:34 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +[alert]
Just checked - `alert` is the yellow style.

I think it may be good to have some standardization of when we use which type of box. What about this:
* `info` (blue) for information about PHP features and how to use them.
* `alert` (yellow) for information on whether or not something can be used in WP Core.
* `warning` (red) for anything really problematic (like using the `wp` namespace prefix).

2022-08-26 11:30 UTC, dingo-d commented on wordpress-coding-standards/php.md
> +The following examples showcase what type hints are currently available in the WordPress Core due to the minimum supported PHP version
I think we can remove the examples for themes and plugins, to reduce any possible confusion. And as you've mentioned, people will have the info box with all the available types 🙂 👍🏼

2022-08-26 12:22 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +[alert]
Oh and on that same note: what about standardizing the order as well ?

I'm thinking:
* CS rules
* Possible code samples
* Usage in Core (if needed)
* PHP feature info (if needed)

That would also imply that the "boxes" at the bottom of this section and for "trait use" would need to be reversed, but we'd be making the docs consistent and predictable for the reader if we have a set order for things.

2022-08-26 12:23 UTC, jrfnl reviewed
See inline comments + the remark about the order of information.

2022-08-26 12:34 UTC, dingo-d commented on wordpress-coding-standards/php.md
> +[alert]
I'll open an issue and once we merge all the others I can open up a new PR with just these changes 👍🏼

2022-08-28 02:06 UTC, jrfnl approved these changes
Approving. There is a stray space in line 425 "code[space][space]new to Core", which I will remove before merging.

Merging this now as @GaryJones is AFK for the next few weeks. If needs be, additional textual tweaks can still be made in a follow up commit.

2022-08-28 02:07 UTC, merged