Spread operator
WordPress/wpcs-docs pull request #105
Opened 2022-08-20 13:13 UTC by dingo-d

This PR depends on #104. Once that is merged, this PR should be rebased to the master branch.

The PR adds rules about the type declaration rules and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

2022-08-28 15:34 UTC, dingo-d commented
I've rebased this so it's ready for review.

2022-09-03 17:20 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +The spread operator can be used for packing arguments in function declarations, and unpacking them in function calls, but cannot be used for array unpacking, until the minimum PHP version has been ra
```suggestion
The spread operator can be used to pack arguments in function declarations and unpack them in function calls. However, it cannot be used for array unpacking until the minimum PHP version has been raised to PHP 7.4.
```

2022-09-03 17:20 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +When using the spread operator, there should be one space, or a new line with the appropriate indentation before the spread operator. There should be no spaces between the spread operator and the var
```suggestion
The spread operator (or splat operator as it's known in other languages) is used for packing arguments in function declarations (variadic functions) and unpacking them in function calls in PHP 5.6. In PHP 7.4, the spread operator is also used for unpacking arrays (string-keyed array unpacking is available since PHP 8.1).

When using the spread operator, there should be one space or a new line with the appropriate indentation before the spread operator. There should be no spaces between the spread operator and the variable/function call it applies to. When combining the spread operator with the reference operator (`&`), there should be no spaces between them.
```

2022-09-05 18:22 UTC, GaryJones approved these changes
One optional suggestion thrown in that I'm not married to. Otherwise ✅ .

2022-09-05 18:22 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +The spread operator (or splat operator as it's known in other languages) is used for packing arguments in function declarations (variadic functions) and unpacking them in function calls in PHP 5.6. I
```suggestion
The spread operator (or splat operator as it's known in other languages) is used for packing arguments in function declarations (variadic functions) and unpacking them in function calls in PHP 5.6. In PHP 7.4, the spread operator is also used for unpacking numerically-indexed arrays, with string-keyed array unpacking available since PHP 8.1.
```

2022-09-09 09:04 UTC, jrfnl requested changes
Left some remarks

2022-09-09 09:04 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +        [...  $foo ],.../*comment*/array_values( $keyed_array )
```suggestion
        [...  $foo ],... array_values( $keyed_array )
```

While relevant for sniffing, I think we can just leave the comment out of the code example.

2022-09-09 09:04 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +_Usage in WordPress Core_
If the PHP info gets moved to the bottom, this paragraph can possibly be removed completely ? (as the PHP info block already mentions all PHP version restrictions)

2022-09-09 09:16 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +The spread operator can only be used once in a function declaration and has to be used with the last parameter.
```suggestion
When used in a function declaration, the spread operator can only be used with the last parameter.
```

2022-09-09 09:29 UTC, jrfnl approved these changes
✅

2022-09-09 09:29 UTC, merged