Include require statements
WordPress/wpcs-docs pull request #111
Opened 2022-08-20 14:16 UTC by dingo-d

This PR depends on #110. Once that is merged, this PR should be rebased to the master branch.

The PR adds rules about the include/require statements and is the continuation of the additions of 'modern' PHP code in the WordPress PHP Coding Standards handbook based on the [make post](https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/) by Juliette Reinders Folmer.

2022-08-26 23:19 UTC, jrfnl requested changes
Left some inline notes.

2022-08-26 23:19 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +It is _strongly recommended_ to use `require[_once]` for unconditional includes.
Suggestion: add a blank line before this line as the first line is about CS, while the second line and after is about recommended "best practices".

2022-08-26 23:19 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +When using `include[_once]` PHP will throw a warning when the file is not found, but will continue execution which will almost certainly lead to other errors/warnings/notices being thrown if your app
```suggestion
When using `include[_once]` PHP will throw a warning when the file is not found, but will continue execution which will almost certainly lead to other errors/warnings/notices being thrown if your application depends on the file having been loaded, potentially leading to security leaks. For that reason, `require[_once]` is generally the better choice as it will throw a `Fatal Error` if the file cannot be found.
```

2022-08-26 23:19 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +Because `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path. There should only be one space between the path and the include/require keywords.
```suggestion
Because `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path. There should only be one space between the include/require keyword and the path.
```

I'm not fully convinced about the first sentence. It feels a bit like a soft recommendation, while it was proposed as a hard rule.

Re: the tweak in the second sentence - IMO this reads more natural as that's the order of in the code.

2022-08-26 23:19 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +require_once     __FILE__ . '/file-name.php';
```suggestion
require_once     __DIR__ . '/file-name.php';
```

2022-08-28 09:41 UTC, dingo-d commented on wordpress-coding-standards/php.md
> +Because `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path. There should only be one space between the path and the include/require keywords.
> Because `include[_once]` and `require[_once]` are language constructs, you mustn't add parentheses around the path.

This reads as a hard rule, the only issue is that it kinda reads like it would cause a fatal error if you add it (which it won't) 🤷🏼‍♂️

2022-08-28 12:46 UTC, jrfnl commented on wordpress-coding-standards/php.md
> +Because `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path. There should only be one space between the path and the include/require keywords.
> Because include[_once] and require[_once] are language constructs, you mustn't add parentheses around the path.

What about using "shouldn't" instead of "mustn't" ?

Or even:
> Because `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path, so those shouldn't be used.

2022-09-03 17:27 UTC, GaryJones commented on wordpress-coding-standards/php.md
> +When using `include[_once]` PHP will throw a warning when the file is not found, but will continue execution which will almost certainly lead to other errors/warnings/notices being thrown if your app
```suggestion
Because `include[_once]` and `require[_once]` are language constructs, they do not need parentheses around the path, so those shouldn't be used. There should only be one space between the path and the include/require keywords.

It is _strongly recommended_ to use `require[_once]` for unconditional includes. When using `include[_once]`, PHP will throw a warning when the file is not found but will continue execution, which will almost certainly lead to other errors/warnings/notices being thrown if your application depends on the file loaded, potentially leading to security leaks. For that reason, `require[_once]` is generally the better choice as it will throw a `Fatal Error` if the file cannot be found.
```

(mostly just comma changes)

2022-09-05 18:24 UTC, GaryJones approved these changes
✅

2022-09-06 06:36 UTC, dingo-d commented
@jrfnl Mind giving this another check, and merging if it's ok?

2022-09-09 09:08 UTC, jrfnl approved these changes
LGTM! Thanks @dingo-d !

2022-09-09 09:08 UTC, merged