Clarify exceptions for using `@return void`
WordPress/wpcs-docs pull request #133
Opened 2023-10-16 15:02 UTC by felixarntz

See https://core.trac.wordpress.org/ticket/59619 and https://github.com/WordPress/wordpress-develop/pull/5484#pullrequestreview-1679058155: The current explanation that `@return void` should only be used outside of bundled themes is missing two other areas where that rule does not apply.

2023-10-16 18:11 UTC, jrfnl reviewed
@felixarntz Thanks for the PR.

Is there a reason for this addition ? Any recent discussion ?

I believe "third party libraries" has no place here as the coding standards do not apply to third party code anyway (unless they would choose to use it), but other than that, I'm fine with adding "PHP compatibility shims".

2023-10-16 18:13 UTC, jrfnl commented
As a side-note: I believe this rule should be changed/removed, but that's outside the scope of this PR.

2023-10-16 18:24 UTC, felixarntz commented
@jrfnl 
> Is there a reason for this addition ? Any recent discussion ?

Nothing other than what I linked in the PR description. This is not about a discussion or change on what we should be doing, it is merely documenting what is the current situation already: All usage of `@return void` is either in bundled themes, bundled third-party libraries, or PHP compatibility shims.

WordPress core does not necessarily control bundled third-party code, therefore this exclusion is more or less mandatory. For example, the bundled libraries PHPMailer and Requests contain `@return void`.

2023-10-16 18:35 UTC, jrfnl commented
> WordPress core does not necessarily control bundled third-party code, therefore this exclusion is more or less mandatory. For example, the bundled libraries PHPMailer and Requests contain `@return void`.

I agree that, as WP bundles third party code in a non-industry standard way, it may not always be clear to contributors what is third party code. However, that still doesn't take anything away from the fact that third party code is always excluded from project specific coding standards, so mentioning it here is redundant and not appropriate.

If at all necessary and not explicit enough already, it could be made more explicit on the introductory pages for the coding standards, but the current change is not the place (as inlining such an explicit exclusion for third party code for one particular rule creates ambiguity as if other rules _would_ apply to external libraries).

2023-10-16 18:38 UTC, felixarntz commented
> However, that still doesn't take anything away from the fact that third party code is always excluded from project specific coding standards, so mentioning it here is redundant and not appropriate.

I disagree that it is redundant. There were questions about this on the linked PR, so clearly this is not obvious, even if you or I know about it.

2023-11-20 09:44 UTC, afercia commented
Chiming in hoping to unblock this conversation :) 
To me, the main issue now is that there is a changeset in core, which is part of the history of the project, that explicitly mentions bundled themes, third-party libraries, and PHP compatibility shims. See https://core.trac.wordpress.org/changeset/56943.

However, [the documentation only mentions bundled themes](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#:~:text=Note%3A%20%40return%20void%20should%20not%20be%20used%20outside%20of%20the%20default%20bundled%20themes).

This inconsistency doesn't help reducing confusion. I see a few issues that should be clarified:
1. The documentation doesn't clarify _why_ `@return void` should not be used.
2. The statement `should not` is different from `must not`. `should not` implies that in some cases, it can be used. It's a recommendation, not a strict rule.

> As a side-note: I believe this rule should be changed/removed, but that's outside the scope of this PR.

That would help simplifying things. 'Always add a return notation' is a way more simple concept rather than 'use return sometimes but sometimes not'. I would vote for making things simpler and always require a return notation.

2023-11-20 15:44 UTC, felixarntz commented
@afercia I agree with most of what you're saying. Except:
> 'Always add a return notation' is a way more simple concept rather than 'use return sometimes but sometimes not'. I would vote for making things simpler and always require a return notation.

I don't think requiring `@return void` is a good call here. Yes, it's consistent in that every function then would get a `@return` annotation, but `@return void` functions don't actually return anything, so it's arguable that that has to be documented explicitly. More importantly though, this would be a significant documentation change with much larger implications than what we're discussing here. Would we go over all WP core functions and add `@return void` to it? That doesn't seem realistic or a good use of our time, and then if we don't do it we have even more inconsistency than now.

I think we should clarify the documentation for the exceptions, then that should be good. I wouldn't overinterpret the "must" in the commit message. Commit messages don't go through any review and I just wrote that without thinking much. That message (like other commit messages) carries no authority on any documentation matters.

2023-11-20 16:36 UTC, jrfnl commented
> @afercia I agree with most of what you're saying. Except:
> 
> > 'Always add a return notation' is a way more simple concept rather than 'use return sometimes but sometimes not'. I would vote for making things simpler and always require a return notation.
> 
> I don't think requiring `@return void` is a good call here. Yes, it's consistent in that every function then would get a `@return` annotation, but `@return void` functions don't actually return anything, so it's arguable that that has to be documented explicitly. More importantly though, this would be a significant documentation change with much larger implications than what we're discussing here. Would we go over all WP core functions and add `@return void` to it? That doesn't seem realistic or a good use of our time, and then if we don't do it we have even more inconsistency than now.
> 
> I think we should clarify the documentation for the exceptions, then that should be good. I wouldn't overinterpret the "must" in the commit message. Commit messages don't go through any review and I just wrote that without thinking much about the difference. That message (like other commit messages) carries no authority on any documentation matters.

While I'd very much like a discussion on _always requiring `@return` tags_ (and did an [extensive write up about why we should](https://github.com/jrfnl/rfcs/blob/feature/docs-always-demand-return-tag/text/0000-docs-always-use-return-tag.md) some years back when an RFC repo opened, but then the repo was closed before I could open a PR), this is not the place for that discussion.

I have already said that the current PR is not acceptable and what should happen instead. The PR needs an update or it won't get merged.

2023-11-20 16:39 UTC, felixarntz commented
@jrfnl 
> I have already said that the current PR is not acceptable and what should happen instead. The PR needs an update or it won't get merged.

I am unclear what should happen instead, I was waiting for a reply from you to my comment https://github.com/WordPress/wpcs-docs/pull/133#issuecomment-1765073168. Based on that, what do you think should happen?

2023-11-20 17:28 UTC, felixarntz commented
@jrfnl PR updated.

2023-11-20 17:55 UTC, felixarntz commented on wordpress-coding-standards.md
> +The WordPress Coding Standards apply to WordPress code. Third-party libraries are not subject to these standards, even when bundled with the main project code. This may occasionally be the case, for
@jrfnl Updated.

2023-11-20 17:59 UTC, jrfnl approved these changes
Thanks for the updating the PR @felixarntz . It will be merged after a second review.

2023-11-21 07:25 UTC, dingo-d requested changes
Left one suggestion, just reads a bit better for me.

2023-11-21 07:25 UTC, dingo-d commented on wordpress-coding-standards.md
> +<h2>Where to (not) apply the coding standards</h2>
```suggestion
<h2>Where not to apply the coding standards?</h2>
```

This reads better considering the paragraph below in my opinion.

2023-11-21 16:30 UTC, dingo-d commented on wordpress-coding-standards.md
> +<h2>Where to (not) apply the coding standards</h2>
To me, with the paragraph below explaining where not to apply them, it reads more like a question (plus _where_ is a question word).

The heading doesn't read with _where_ as a conjunction or a relative pronoun.

2023-11-21 16:52 UTC, felixarntz commented on wordpress-coding-standards.md
> +<h2>Where to (not) apply the coding standards</h2>
It's not a question though. For example, the common heading "How to do xyz" also starts with a question word, but it's not a question.

Generally, most headings aren't sentences, including this one, so unless we make it an actual question (e.g. "Where should the coding standards not be applied?"), it's not a question either.

The way the words "Where" and "How" are used in this kind of heading is probably closest to "{This section describes...} Where not to apply the coding standards". So I'd argue that "where" is closest to a conjunction here.

2023-11-21 16:59 UTC, felixarntz commented on wordpress-coding-standards.md
> +Third-party libraries are not subject to these standards, even when bundled with the main project code. This may occasionally be the case, for example WordPress core bundles several third-party libra
@GaryJones The 2nd sentence sounds great, but for the 1st one, I'm not sure about which benefits this would have over the current way. It just shifts main clause and sub clause as far as I can tell, which I think in this case makes for a worse order, since IMO:
* The main aspect to clarify is that third-party libraries are exempt, so that makes sense to come first.
* The "even when bundled" bit ties to the sentence that follows, so that makes sense to come second.

2023-11-21 17:03 UTC, felixarntz commented on wordpress-coding-standards.md
> +Third-party libraries are not subject to these standards, even when bundled with the main project code. This may occasionally be the case, for example WordPress core bundles several third-party libra
I've incorporated your suggestions without changing the main clause sub clause order in https://github.com/WordPress/wpcs-docs/pull/133/commits/b0d5d5fdf75b0bcb94f26f55df02942fc1268c96.

2023-11-21 19:47 UTC, jrfnl commented on wordpress-coding-standards.md
> +<h2>Where to (not) apply the coding standards</h2>
I agree with the "don't apply".

2023-11-22 14:59 UTC, felixarntz commented on wordpress-coding-standards.md
> +<h2>Where to (not) apply the coding standards</h2>
Updated to "Where do the coding standards not apply?"

2023-11-22 17:19 UTC, dingo-d approved these changes

2023-11-22 19:31 UTC, jrfnl approved these changes
LGTM, should "not" be made italic to draw more attention to it ?

2023-11-23 07:30 UTC, GaryJones approved these changes

2023-11-28 15:33 UTC, felixarntz commented
@jrfnl Happy to make it italic if others agree? @GaryJones @dingo-d

2023-11-28 23:02 UTC, dingo-d commented
Yup, go ahead 🙂

2023-11-28 23:03 UTC, felixarntz commented
@dingo-d Done :)

2023-11-28 23:17 UTC, merged