Update accessibility.md
WordPress/wpcs-docs pull request #54
Opened 2021-05-14 16:43 UTC by azhiya

As agreed by the accessibility team, the existing Accessibility standards have been updated to provide better guidance.

2021-05-17 09:26 UTC, GaryJones requested changes
A few suggestions.

2021-05-17 09:26 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +Code integrated into the WordPress ecosystem - including WordPress core, WordPress.org websites, and official plugins, is expected to conform to the Web Content Accessibility Guidelines, version 2.1,
```suggestion
Code integrated into the WordPress ecosystem - including WordPress core, WordPress.org websites, and official plugins, is expected to conform to the Web Content Accessibility Guidelines (WCAG), version 2.1, at level AA. 
```

Allows for using the abbreviation later on.

2021-05-17 09:26 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +**Level A** success criteria address concerns considered to be first, accessibility barriers on a very wide scale that will prevent many people from accessing the site and, second, easily accomplishe
> **Level A** success criteria address concerns considered to be first

This doesn't make sense?

2021-05-17 09:26 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +Techniques (code examples, resources, and tests) for guidance and success criteria that can help in making content more accessible, they are divided into three categories:
```suggestion
Techniques (code examples, resources, and tests) for guidance and success criteria that can help in making content more accessible, are divided into three categories:
```

2021-05-17 09:26 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +[Mozilla Accessibility - Users first, no matter their abilities](https://blog.mozilla.org/accessibility/)
```suggestion
- [WebAIM: Web Accessibility In Mind](https://webaim.org/) (see Articles and Resources)
- [Government Digital Service](https://gds.blog.gov.uk)
- [Accessibility in government](https://accessibility.blog.gov.uk/) 
- [Blog | TPG – The Accessibility Experts](https://developer.paciellogroup.com/blog/)
- [Web Accessibility Blog (Deque)](https://www.deque.com/blog/)
- [Tink - Léonie Watson](https://tink.uk) (Léonie Watson)
- [Adrian Roselli](https://adrianroselli.com)
- [Scott O'Hara](https://www.scottohara.me)
- [Joe Dolson](https://www.joedolson.com/blog)
- [Sarah Higley](https://sarahmhigley.com/) 
- [Marco's Accessibility Blog](https://www.marcozehe.de/) 
- [Karl Groves](https://karlgroves.com/) 
- [Inclusive Components](https://inclusive-components.design) (Heydon Pickering)
- [Accessibility London (London, United Kingdom)](https://www.meetup.com/London-Accessibility-Meetup/) (London accessibility meetup: they live stream meetups on youtube)
- [24 Accessibility](https://www.24a11y.com/)
- [Mozilla Accessibility - Users first, no matter their abilities](https://blog.mozilla.org/accessibility/)
```

Making it a list should make it easier for screen reader users to follow, than line-break-filled link after link after link.

2021-05-17 09:26 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +[ARIA Landmarks Example: HTML Sectioning Elements](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html)
```suggestion
- [Accessibility Support](https://a11ysupport.io/) (Will your code work with assistive technologies?)
- [Accessibility APIs: A Key To Web Accessibility](https://www.smashingmagazine.com/2015/03/web-accessibility-with-accessibility-api/) (by Léonie Watson)  
- [How accessibility trees inform assistive tech](https://hacks.mozilla.org/2019/06/how-accessibility-trees-inform-assistive-tech/) (by Hidde de Vries) 
- [What is this thing and what does it do?](https://www.youtube.com/watch?v=YLihNhn_MO4 ) (presentation by Karl Groves)
- [The Browser Accessibility Tree](https://developer.paciellogroup.com/blog/2015/01/the-browser-accessibility-tree/) (by Steve Faulkner)
- [Brief history of browser accessibility support](https://www.paciellogroup.com/blog/2011/10/brief-history-of-browser-accessibility-support/) (by Steve Faulkner) 
- [ARIA Landmarks Example: General Principles](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/)
- [ARIA Landmarks Example: HTML Sectioning Elements](https://www.w3.org/TR/wai-aria-practices/examples/landmarks/HTML5.html) 
```

2021-05-18 10:31 UTC, azhiya commented on wordpress-coding-standards/accessibility.md
> +**Level A** success criteria address concerns considered to be first, accessibility barriers on a very wide scale that will prevent many people from accessing the site and, second, easily accomplishe
Hmmm, I see what you mean. How about
**Level A** success criteria address concerns considered to be accessibility barriers on a very wide scale that will prevent many people from accessing the site and the minimum set of accomplished goals required for the majority of web-based interfaces.

2021-05-18 16:20 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +**Level A** success criteria address concerns considered to be first, accessibility barriers on a very wide scale that will prevent many people from accessing the site and, second, easily accomplishe
LGTM.

2021-05-21 14:03 UTC, azhiya commented on wordpress-coding-standards/accessibility.md
> +**Level A** success criteria address concerns considered to be first, accessibility barriers on a very wide scale that will prevent many people from accessing the site and, second, easily accomplishe
@GaryJones I'm trying to change this but I don't think I'm accessing the right area.

2021-05-21 23:56 UTC, GaryJones commented on wordpress-coding-standards/accessibility.md
> +**Level A** success criteria address concerns considered to be first, accessibility barriers on a very wide scale that will prevent many people from accessing the site and, second, easily accomplishe
@azhiya I've updated it.

2021-05-21 23:57 UTC, GaryJones commented
@azhiya With the Level A description fixed, is this ready for review again?

2021-05-26 09:19 UTC, azhiya commented
Yes, thank you @GaryJones

2021-05-26 09:29 UTC, GaryJones approved these changes

2021-05-26 09:29 UTC, merged

2021-06-04 15:50 UTC, azhiya commented
Thank you @GaryJones