Update css.md
WordPress/wpcs-docs pull request #70
Opened 2022-05-02 05:40 UTC by ntwb

Follow up to #66 to update markdown format for https://developer.wordpress.org/coding-standards/wordpress-coding-standards/css/

2022-05-02 05:59 UTC, jrfnl requested changes
This document still contains a LOT of HTML which should probably be converted to markdown properly.

2022-05-02 05:59 UTC, jrfnl commented on wordpress-coding-standards/css.md
> +Top/Right/Bottom/Left (TRBL/trouble) should be the order for any relevant properties (e.g. margin), much as the order goes in values. Corner specifiers (e.g. `border-radius-*-*`) should be top-left,
```suggestion
Top/Right/Bottom/Left (TRBL/trouble) should be the order for any relevant properties (e.g. `margin`), much as the order goes in values. Corner specifiers (e.g. `border-radius-*-*`) should be `top-left`, `top-right`, `bottom-right`, `bottom-left`. This is derived from how shorthand values would be ordered.
```

2022-05-02 06:14 UTC, ntwb commented on wordpress-coding-standards/css.md
> +Top/Right/Bottom/Left (TRBL/trouble) should be the order for any relevant properties (e.g. margin), much as the order goes in values. Corner specifiers (e.g. `border-radius-*-*`) should be top-left,
Ha, the linter was only throwing "no html" warnings here, but the verbiage is clearly HTML, thanks 😏

I've started updating the rest of the HTML and will push those changes here shortly too

2022-05-02 06:57 UTC, dingo-d commented on wordpress-coding-standards/css.md
> +- Multiple comma-separated values for one property should be separated by either a space or a newline. For better readability newlines should be used for lengthier multi-part values such as those for
```suggestion
- Multiple comma-separated values for one property should be separated by either a space or a newline. For better readability, newlines should be used for lengthier multi-part values such as those for shorthand properties like `box-shadow` and `text-shadow`, including before the first value. Values should then be indented one level in from the property.
```

Just to make it consistent with the code values in the other list items.

2022-05-02 06:57 UTC, dingo-d commented on wordpress-coding-standards/css.md
> +- Lists of values within a value, like within rgba(), should be separated by a space.
```suggestion
- Lists of values within a value, like within `rgba()`, should be separated by a space.
```

2022-05-02 06:59 UTC, dingo-d commented on wordpress-coding-standards/css.md
> +- Know when to use the height property. It should be used when you are including outside elements (such as images). Otherwise use line-height for more flexibility.
```suggestion
- Know when to use the `height` property. It should be used when you are including outside elements (such as images). Otherwise use `line-height` for more flexibility.
```

2022-05-02 07:00 UTC, dingo-d commented on wordpress-coding-standards/css.md
> +- Do not restate default property &amp; value combinations (for instance `display: block;` on block-level elements).
Do we still need to use `&amp;` here? I know there were some parser issues, but if we're now using markdown these might have been fixed 🤷🏼‍♂️

2022-05-02 07:01 UTC, dingo-d requested changes
Left some minor comments, otherwise looks good to me 👍🏼

2022-05-02 07:07 UTC, ntwb commented on wordpress-coding-standards/css.md
> +- Do not restate default property &amp; value combinations (for instance `display: block;` on block-level elements).
There's no instances of `& `  standalone elsewhere in the code, so let's not risk it in this PR (in the hope of keeping any potential reverts to a minimum)

<img width="298" alt="image" src="https://user-images.githubusercontent.com/1016458/166197071-cccce432-5f25-4294-b796-a689e8ff4df8.png">

2022-05-02 07:09 UTC, ntwb commented on wordpress-coding-standards/css.md
> +- Multiple comma-separated values for one property should be separated by either a space or a newline. For better readability newlines should be used for lengthier multi-part values such as those for
Agreed, I was doing these offline, so should be fixed in https://github.com/WordPress/wpcs-docs/pull/70/commits/a70b8aa4ad2b45618b07b8def74749f83da912a6

2022-05-02 07:09 UTC, ntwb commented on wordpress-coding-standards/css.md
> +- Lists of values within a value, like within rgba(), should be separated by a space.
Agreed, I was doing these offline, so should be fixed in https://github.com/WordPress/wpcs-docs/pull/70/commits/a70b8aa4ad2b45618b07b8def74749f83da912a6

2022-05-02 07:09 UTC, ntwb commented on wordpress-coding-standards/css.md
> +- Know when to use the height property. It should be used when you are including outside elements (such as images). Otherwise use line-height for more flexibility.
Agreed, I was doing these offline, so should be fixed in https://github.com/WordPress/wpcs-docs/pull/70/commits/a70b8aa4ad2b45618b07b8def74749f83da912a6

2022-05-02 07:10 UTC, ntwb commented
This can be re-reviewed now, I think I've got everything 🤞🏼

2022-05-02 07:12 UTC, dingo-d approved these changes

2022-05-02 08:52 UTC, jrfnl reviewed
Just one small remark (and one outside the scope of this PR to be addressed separately).

2022-05-02 08:52 UTC, jrfnl commented on wordpress-coding-standards/css.md
> +- Line height should also be unit-less, unless necessary to be defined as a specific pixel value. This is more than just a style convention, but is worth mentioning here. More information: [https://m
```suggestion
- Line height should also be unit-less, unless necessary to be defined as a specific pixel value. This is more than just a style convention, but is worth mentioning here. More information: <https://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/>.
```

2022-05-02 08:52 UTC, jrfnl commented on wordpress-coding-standards/css.md
> +- Comments should be formatted much as PHPDoc is. The [CSSDoc](https://web.archive.org/web/20070601200419/http://cssdoc.net/) standard is not necessarily widely accepted or used but some aspects of i
[**Outside the scope of this PR**]

The reference to PHPDoc reads weird here, especially without a link. Also it is ambiguous as it encompasses a lot of standards.

It may be clearer to be more explicit in what is meant, like "use `/* ... */` style comments" or "use multiline `/** ... */ docblock-like comments".

2022-05-02 09:50 UTC, ntwb commented on wordpress-coding-standards/css.md
> +- Comments should be formatted much as PHPDoc is. The [CSSDoc](https://web.archive.org/web/20070601200419/http://cssdoc.net/) standard is not necessarily widely accepted or used but some aspects of i
For sure, it's a tough one, CSSDoc was based off of PHPDoc, I've quickly tweaked that comment here for some context clarity, but for sure this should be updated and reworded to make this clearer

> Comments should be formatted similar to how PHPDoc is implemented, the defunct [CSSDoc](https://web.archive.org/web/20070601200419/http://cssdoc.net/) standard proposal is not widely accepted or used (hence the archive.org link) but some aspects of it have been somewhat adopted over time. Section/subsection headers should have newlines before and after. Inline comments should not have empty newlines separating the comment from the item to which it relates.

2022-05-03 10:20 UTC, GaryJones requested changes

2022-05-03 10:20 UTC, GaryJones commented on wordpress-coding-standards/css.md
> +- Refrain from using over-qualified selectors, `div.container` can simply be stated as `.container`
```suggestion
- Attribute selectors should use double quotes around values.
- Refrain from using over-qualified selectors, `div.container` can simply be stated as `.container`.
```

2022-05-03 10:20 UTC, GaryJones commented on wordpress-coding-standards/css.md
> +- Use shorthand (except when overriding styles) for `background`, `border`, `font`, `list-style`, `margin`, and `padding` values as much as possible. (For a shorthand reference, see [CSS Shorthand](h
```suggestion
- Use shorthand, except when overriding styles, for `background`, `border`, `font`, `list-style`, `margin`, and `padding` values as much as possible. For a shorthand reference, see [CSS Shorthand](https://codex.wordpress.org/CSS_Shorthand).
```

No real benefit to those extra parentheses IMO.

2022-05-03 10:20 UTC, GaryJones commented on wordpress-coding-standards/css.md
>  Top/Right/Bottom/Left (TRBL/trouble) should be the order for any relevant properties (e.g. margin), much as the order goes in values. Corner specifiers (e.g. border-radius-*-*) should be top-left, to
```suggestion
Top/Right/Bottom/Left (TRBL/trouble) should be the order for any relevant properties (e.g. `margin`), much as the order goes in values. Corner specifiers (e.g. `border-radius-*-*`) should be ordered as top-left, top-right, bottom-right, bottom-left. This is derived from how shorthand values would be ordered.
```

2022-05-03 10:20 UTC, GaryJones commented on wordpress-coding-standards/css.md
> +Updated on 2/13/2014, after [[27174](https://core.trac.wordpress.org/changeset/27174)]:
```suggestion
Updated on 2014-02-13, after [[27174](https://core.trac.wordpress.org/changeset/27174)]:
```

Use international date format.

2022-05-03 10:20 UTC, GaryJones commented on wordpress-coding-standards/css.md
> +- Line height should also be unit-less, unless necessary to be defined as a specific pixel value. This is more than just a style convention, but is worth mentioning here. More information: <https://m
Something funky going on with the link at the end of this line - note the uncoloured `s` and apparent difference in displayed vs actual link:

<img width="1492" alt="Screenshot 2022-05-03 at 11 11 39" src="https://user-images.githubusercontent.com/88371/166436644-85f39e3e-0f84-45db-a7c7-15361b654104.png">

2022-05-03 10:20 UTC, GaryJones commented on wordpress-coding-standards/css.md
> +- Do not restate default property &amp; value combinations (for instance `display: block;` on block-level elements).
```suggestion
- Do not restate default property and value combinations (for instance `display: block;` on block-level elements).
```

Let's just remove it and be done. Throwing "property & value" into Google Translate and selecting random locales showed that the ampersand isn't used for some anyway, so may as well just use "and" instead. There's no ambiguity here that the ampersand is needed for anyway.

2022-05-04 01:53 UTC, ntwb commented on wordpress-coding-standards/css.md
> +- Line height should also be unit-less, unless necessary to be defined as a specific pixel value. This is more than just a style convention, but is worth mentioning here. More information: <https://m
The `s` does have a green background, as does the period at the end of the sentence after the URL
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/1016458/166613445-bcc3566e-eb4c-4d05-9dd3-9069b1f40435.png">

2022-05-04 07:18 UTC, GaryJones approved these changes

2022-05-20 09:35 UTC, jrfnl commented
@ntwb I've taken the liberty to rebase this PR (without changes) as the merge of #77 caused a conflict.

2022-05-20 11:28 UTC, jrfnl approved these changes
Not sure what this was still waiting for. Looks good and with all the approvals, merging this now.

2022-05-20 11:29 UTC, merged